apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-14vw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-14vw
    app.kubernetes.io/part-of: tkrw-pr714-0075-0025-app
  name: devfile-sample-14vw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-14vw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-14vw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0025-tenant/tkrw-pr714-0075-0025-app/devfile-sample-14vw@sha256:329dc0b2eeeaedf6782a98641dbd2e1986062f314cea0de8a18fd4a673eaf085
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
