apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-14vw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0025-tenant/tkrw-pr714-0075-0025-app/devfile-sample-14vw@sha256:329dc0b2eeeaedf6782a98641dbd2e1986062f314cea0de8a18fd4a673eaf085
        name: my-nodejs
        resources: {}
status: {}
